### ISSUE TITLE
Error: Illegal arguments: string, undefined

### ISSUE THREAD

**Issue by damion-w** [damion-w/micro-journal#1]
I am getting this error when logging in:

{
"message": "Illegal arguments: string, undefined",
"stack": "Error: Illegal arguments: string, undefined\n    at Object.bcrypt.compareSync (/Users/damion/ga-proj/micro-journal/node_modules/bcryptjs/dist/bcrypt.js:265:19)\n    at Object.comparePass (/Users/damion/ga-proj/micro-journal/services/auth/auth-helpers.js:4:19)\n    at /Users/damion/ga-proj/micro-journal/services/auth/local.js:19:34\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}

In a nutshell, when findByUsername() is called to get the row for the user trying to log in, the passwordDigest field is undefined:

static findByUsername(username) {
        return db.oneOrNone(
            `SELECT * FROM users WHERE username = $1`,
            username)
        .then((user => {
            console.log(user.passwordDigest)
            if (user) return new this(user)
            else throw new Error('User not found')
        }))
    }

I checked the DB and there is indeed a value there for the user.

userPassword is flowing to my comparePass function, but databasePassword is not:
function comparePass(userPassword, databasePassword) {
    console.log(databasePassword)
    return bcrypt.compareSync(userPassword, databasePassword)
}

Not much on Google, just found this article which was unhelpful: https://stackoverflow.com/questions/34982964/bcrypt-error-illegal-arguments-string-unidentified/45507725

**Comment by jlr7245** [comment]
keep in mind that your `password_digest` is not `passwordDigest` but the snake case version! you've named the database column `passport_digest` so that's what will come out once you run `return db.oneOrNone(..).then(user ...`   i think that switching to `password_digest` everywhere would fix this. here specifically: https://github.com/damion-w/micro-journal/commit/e6670f761197c0e56fb88850208f800f83963fff#r41453819

similarly i think you should add the unique username constraint in your database setup. eventually when you create two users with the same username you'll wind up getting an error from `return db.oneOrNone` as you'll get more than one.

**Comment by damion-w** [comment]
Thanks J!  I learned that when I'm doing a FindByUsername(), when I do a Object.assign(this, user), the name of the properties that are created on the this object are equal to the names of the columns in the table.
